/*
 * FrontUi.java
 *
 * Created on 07 December 2006, 08:55
 */

package morsetheu;

import javax.swing.UIManager;

/**
 *
 * @author  alekz
 */
public class FrontUi extends javax.swing.JFrame {
    
    /** Creates new form FrontUi */
    public FrontUi() {
        String lookAndFeel = UIManager.getSystemLookAndFeelClassName();//CrossPlatformLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(lookAndFeel);
        } catch (Exception e) { }
        initComponents();
        this.getRootPane().setDefaultButton(this.doMorseTheu);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        rows = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        columns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doMorseTheu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        morseTheuOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Whywhywhy");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        getAccessibleContext().setAccessibleName("Morse Theu infinite series");
        getAccessibleContext().setAccessibleDescription("Morse Theu");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Morse-Theu infinite series"));
        jPanel1.setName("MT");
        rows.setText("2");
        rows.setMinimumSize(new java.awt.Dimension(40, 19));
        rows.setPreferredSize(new java.awt.Dimension(40, 19));

        jLabel1.setText("iterations");

        columns.setText("2");
        columns.setPreferredSize(new java.awt.Dimension(40, 19));

        jLabel2.setText("columns");

        doMorseTheu.setMnemonic('c');
        doMorseTheu.setText("calc!");
        doMorseTheu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doMorseTheuMouseClicked(evt);
            }
        });

        morseTheuOutput.setColumns(20);
        morseTheuOutput.setLineWrap(true);
        morseTheuOutput.setRows(5);
        jScrollPane1.setViewportView(morseTheuOutput);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(rows, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(columns, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 255, Short.MAX_VALUE)
                        .add(doMorseTheu)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rows, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(columns, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(doMorseTheu))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped
    
    private void doMorseTheuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doMorseTheuMouseClicked
// TODO add your handling code here:
        try{
            Integer rowCount = Integer.parseInt(rows.getText());
            Integer columnCount = Integer.parseInt(columns.getText());
            
            this.morseTheuOutput.setText("");
            this.morseTheuOutput.setColumns(columnCount);
            
            String starter = "0";
            for (int i=0; i<rowCount; i++){
                starter = starter.replace("0","ZA");
                starter = starter.replace("1","01");
                starter = starter.replace("ZA","10");
            }
            
            int i=0;
            try {
                for (i=0; i<starter.length(); i+=columnCount){
                    this.morseTheuOutput.append(starter.substring(i,i+columnCount)+"\n");
                }
            }catch(Exception e){
                this.morseTheuOutput.append(starter.substring(i)+"\n");
            }
            
            //this.morseTheuOutput.setText(starter);
        } catch (Exception e){}
    }//GEN-LAST:event_doMorseTheuMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontUi().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField columns;
    private javax.swing.JButton doMorseTheu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea morseTheuOutput;
    private javax.swing.JTextField rows;
    // End of variables declaration//GEN-END:variables
    
}
